src/BusinessGear/Controllers/CollectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BusinessGear.Data;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace BusinessGear.Controllers
{
    public class CollectionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CollectionController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet("/collection")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("/collection/productdetail/{id}")]
        public IActionResult ProductDetail(int id)
        {
            var model = _context.Products.Include(x => x.Category).First(p => p.Id == id);

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }
    }
}

src/BusinessGear/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BusinessGear.Controllers {

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/BusinessGear/Views/Home/Index.cshtml
@{
    ViewBag.Title = "BusinessGear";
    ViewBag.Css = "/css/site.css";
}

<header class="container">
    @Html.Partial("HeaderBrandPartial")
    <div class="welcome-header">
        <h1>Custom optimised software solutions</h1>
        <h2>We'll fulfill your software demands</h2>
    </div>
    <div class="row top-body-row">
        <div class="col-md-12">
            <div class="let-us-know">
                <h2>Let us know if you're interested!</h2>
                <form id="interestForm" action="#" method="post">
                    <div class="form-inputs">
                        <input id="interestEmail" type="email" placeholder="Enter your e-mail address" required>
                        <input id="interestSubmit" type="submit" value="Get started">
                    </div>
                </form>
            </div>
        </div>
    </div>
</header>

<div class="container body-container">
    <section class="expectations">
        <div class="section-split">
            <div class="section-text">
                <h2><span>What you can expect from us</span></h2>
                <hr>
            </div>
        </div>
        <div class="row row-margins">
            <div class="panels-wrapper">
                <div class="col-md-4">
                    <div class="panel">
                        <div class="panel-title">
                            <b><i class="fa fa-desktop"></i>&ensp;Custom Solution</b>
                        </div>
                        <div class="panel-body">
                            <p>
                                You don't have to worry
                                about software which doesn't
                                cover your idea for 100%.
                                We will take care of the gaps
                                and make sure the software
                                fits your demands.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="panel">
                        <div class="panel-title">
                            <b><i class="fa fa-tachometer"></i>&ensp;Guaranteed Support</b>
                        </div>
                        <div class="panel-body">
                            <p>
                                You bought our software
                                but you find out it could
                                use some upgrades here
                                and there? Fear not, as we
                                will maintain the software
                                to keep it optimal and up to
                                date for you.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="panel">
                        <div class="panel-title">
                            <b><i class="fa fa-heart"></i>&ensp;Our customer, our king</b>
                        </div>
                        <div class="panel-body">
                            <p>
                                If you ever bought a software
                                from us and find yourself in
                                need of a new software solution
                                for anything else, then you'll
                                get a 15% discount on your next
                                software.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="showcase">
        <div class="section-split">
            <div class="section-text">
                <h2><span>A few from our showcase</span></h2>
                <hr>
            </div>
        </div>
        <div class="row gray-wrapper-row" ng-app="app" ng-controller="ProductsController as vm">
            <div class="col-md-12">
                <div ng-repeat="n in vm.range(1, (vm.products.length / 3) + vm.extra) | limitTo: 1">
                    <div class="row">
                        <div class="panels-wrapper">
                            <div ng-repeat="product in vm.products.slice((n - 1) * 3, n * 3)">
                                <div class="col-md-4">
                                    <div class="panel">
                                        <a href="/Collection/ProductDetail/{{ product.id }}">
                                            <div class="panel-image">
                                                <img class="img-responsive" src="http://lorempixel.com/270/211"
                                                     alt="Lorem Ipsum">
                                            </div>
                                            <div class="panel-image-title">
                                                <h3>{{ product.name }}</h3>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="full-collection">
                <p>
                    <a asp-controller="Collection" asp-action="Index" class="default-a">
                        See full collection &DoubleRightArrow;
                    </a>
                </p>
            </div>
        </div>
    </section>
    <section class="appointment-steps">
        <div class="section-split" style="margin-top: 0;">
            <div class="section-text">
                <h2><span>This is how it works</span></h2>
                <hr>
            </div>
        </div>
        <div class="row row-margins">
            <div class="col-lg-offset-1 col-md-offset-1 col-lg-6 col-md-6 col-sm-12">
                <div class="big-img">
                    <div class="img-panel">
                        <p class="first">
                            All you simply have to do
                            is submit your email address
                            and we'll contact you within
                            72 hours. This can be achieved by
                            filling out your e-mail
                            address at the <a href="#"
                                              style="font-weight: bold; text-decoration: underline !important;">top</a>
                            of the page.
                        </p>
                        <p class="second">
                            We'll analyze what has to
                            be done and prepare everything
                            that's needed to get to work
                            on your software as soon
                            as possible.
                        </p>
                        <p class="third">
                            After that everything that has
                            to be done has been analysed
                            and prepared correctly, we'll
                            start building your software
                            infrastructure right away.
                        </p>
                        <p class="fourth">
                            After we've build the product,
                            we'll present it to you so that
                            you have the basic understanding
                            of how the software works
                            be used. Of course the software
                            will be user friendly and will
                            require just a short time to learn.
                        </p>
                    </div>
                    <img class="img-responsive" src="http://www.enudge.com.au/images/dynamic_element_email_bg.jpg"
                         alt="Big picture">
                </div>

            </div>
            <div class="col-md-5 col-sm-12">
                <div class="step-by-step">
                    <ol id="howItWorks" class="no-list-style">
                        <li id="first">
                            <span class="big-round-num clickable">1</span><span class="clickable">You let us know</span>
                        </li>
                        <li id="second">
                            <span class="big-round-num clickable">2</span><span class="clickable">We analyse & prepare</span>
                        </li>
                        <li id="third">
                            <span class="big-round-num clickable">3</span><span class="clickable">We build the infrastructure</span>
                        </li>
                        <li id="fourth">
                            <span class="big-round-num clickable">4</span><span class="clickable">You receive complete product</span>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="about-us">
        <div class="section-split">
            <div class="section-text">
                <h2><span>About Us</span></h2>
                <hr>
            </div>
        </div>
        <div class="row gray-wrapper-row">
            <div class="col-md-12">
                <div class="row" style="margin-bottom: 25px;">
                    <div class="portrait">
                        <div class="col-md-offset-1 col-md-5 col-xs-12">
                            <div class="portrait-img">
                                <img src="~/img/about_us/trump.jpg"
                                     alt="Image of Rene Uhliar, one of the developers">
                            </div>
                        </div>
                        <div class="col-md-3 col-md-offset-right-3 col-xs-12">
                            <div class="portrait-description">
                                <p>
                                    Hi, my name is this. I'm this old.
                                    I've bla bla years experience as
                                    software engineer and looks like
                                    I wanna make some more. Building software
                                    is my passion and love to do it
                                    ever since.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-margins" style="margin-top: 25px;">
                    <div class="portrait">
                        <div class="after col-md-3 col-md-offset-3 col-xs-12">
                            <div class="portrait-description reverse">
                                <p>
                                    Lorem ipsum dolor sit amet,
                                    consectetuer adipiscing elit.
                                    Aenean commodo ligula eget dolor.
                                    Aenean massa. Cum sociis natoque penatibus
                                    et magnis dis parturient montes,
                                    nascetur ridiculus mus.
                                </p>
                            </div>
                        </div>
                        <div class="before col-md-6 col-xs-12">
                            <div class="portrait-img reverse">
                                <img src="~/img/about_us/stupid.jpg" alt="Image of Maros Uhliar, head developer">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="push"></div>
</div>